### PR TITLE
Use a single classloader for java 11 if environment variable is set

### LINKED ISSUE #412: Java11: Static variable appears to be difference instance even though it's in the same class.
#### Repro steps

Provide the steps required to reproduce the problem:

1. Create Function.java below.
```
package com.azure.yutobo.func;

import com.microsoft.azure.functions.ExecutionContext;
import com.microsoft.azure.functions.HttpMethod;
import com.microsoft.azure.functions.HttpRequestMessage;
import com.microsoft.azure.functions.HttpResponseMessage;
import com.microsoft.azure.functions.HttpStatus;
import com.microsoft.azure.functions.annotation.AuthorizationLevel;
import com.microsoft.azure.functions.annotation.FunctionName;
import com.microsoft.azure.functions.annotation.HttpTrigger;

import java.util.Optional;

public class Function {
    static final Person person  = new Person();

    @FunctionName("foo")
    public HttpResponseMessage foo(
            @HttpTrigger(
                name = "req",
                methods = {HttpMethod.GET, HttpMethod.POST},
                authLevel = AuthorizationLevel.ANONYMOUS)
                HttpRequestMessage<Optional<String>> request,
            final ExecutionContext context) {
        context.getLogger().info("foo processed a request.");
        return request.createResponseBuilder(HttpStatus.OK).body("Foo: " + person.).build();
    }

    @FunctionName("bar")
    public HttpResponseMessage bar(
            @HttpTrigger(
                name = "req",
                methods = {HttpMethod.GET, HttpMethod.POST},
                authLevel = AuthorizationLevel.ANONYMOUS)
                HttpRequestMessage<Optional<String>> request,
            final ExecutionContext context) {
        context.getLogger().info("bar processed a request.");
        return request.createResponseBuilder(HttpStatus.OK).body("Bar: " + person).build();
    }
}
```
```
package com.azure.yutobo.func;

class Person {
    String name = "";
    int age = 18;

    Person() {}

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + age;
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Person other = (Person) obj;
        if (age != other.age)
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        } else if (!name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public String toString() {
        return "Person [age=" + age + ", name=" + name + "]";
    }
}

```

2. access Foo & Bar endpoints.

#### Expected behavior

Foo & Bar methods show the same output because they share the same class variable.

#### Actual behavior

Foo & Bar methods show the different output like below.
image

I found that there are separate class variables of Function.class in the heap.
image

And, Function.class loaded twince by the different URLClassLoader.
Apparently, you don't check whether Function.class is already loaded or not.

#### Known workarounds
I couldn't find workarounds.

#### Impact
- There appears to be no ways to share the class variable even methods are in the same class.
- I think we can't make Double-checked locked instance to get Singleton in multi-thread environment.

### LINKED ISSUE #465: Java11: v3 - Static variable appears to be in different instance even though it's in the same class.
#### Investigative information

Using a static variable in java 11 appears to be treated as different instance even though it exists in the same class. 
The issue is similar to #412 which will be fixed in v3 with an application setting. 

#### Repro steps

Use a static variable in a Java function and update it from multiple objects.

#### Expected behavior

The variable must be static across all objects. 

#### Actual behavior

The variable appears to be in different instance and updated individually in every instance.

#### Related information 
This issue will be fixed in v3 provided `FUNCTIONS_WORKER_JAVA_V3_SINGLE_CLASSLOADER` application setting/environment variable is set to true. If the variable is set to false or if left unset, the original behavior is retained.

This issue will be a break change in v4 with no application setting/environment variable need and updates on it can be found at https://github.com/Azure/Azure-Functions/issues/1997

### PR DESCRIPTION
**Pull request by shreyas-gopalakrishna**
If the `FUNCTIONS_WORKER_JAVA_SINGLE_CLASSLOADER` environment variable is set to true then the following changes are made
- For java 11 a synchronized singleton classloader is created for usage 
- This fixes the issue - multiple instances of the static variable even though it's in the same class

#412

### CODE REVIEW

File: src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java [hunk 1]
```diff
@@ -22,11 +22,32 @@ public ClassLoader createClassLoader() {
...
+    /**
+     * @param urlsForClassLoader Array of URLs to construct a new URLClassLoader
+     * @return single instance of URLClassLoader
+     */
+    private URLClassLoader getURLClassLoaderInstance(URL[] urlsForClassLoader) {
+        if (classLoaderInstance == null) {
+            synchronized (URLClassLoader.class) {
+                if (classLoaderInstance == null) {
+                    classLoaderInstance = new URLClassLoader(urlsForClassLoader);
+                    loadDrivers(classLoaderInstance);
```
Comment (trask) [inline src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java]: extract to function to reuse from above also

File: src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java [hunk 2]
```diff
@@ -19,12 +19,36 @@ public EnhancedClassLoaderProvider() {
...
+    /**
+     * Create and return a singleton URL classloader
+     * @return instance of URLClassLoader
+     */
+    private URLClassLoader getURLClassLoaderInstance() {
+        if (classLoaderInstance == null) {
+            synchronized (lock) {
+                if (classLoaderInstance == null) {
+                    URLClassLoader loader = createURLClassLoaderInstance();
+                    loadDrivers(loader);
```
Comment (trask) [inline src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java]: looks like `loadDrivers` can be moved to `createURLClassLoaderInstance`

File: src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java [hunk 3]
```diff
@@ -19,9 +19,33 @@ public EnhancedClassLoaderProvider() {
      */
     @Override
     public ClassLoader createClassLoader() {
+        if(Helper.isCustomURLClassLoader()) {
+            return getURLClassLoaderInstance();
+        }else{
+            URLClassLoader classLoader = createURLClassLoaderInstance();
+            return classLoader;
```
Comment (trask) [inline src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java]:
```suggestion
            return createURLClassLoaderInstance();
```

File: src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java [hunk 4]
```diff
@@ -19,9 +19,33 @@ public EnhancedClassLoaderProvider() {
...
+    /**
+     * Create and return a singleton URL classloader
+     * @return instance of URLClassLoader
+     */
+    private URLClassLoader getURLClassLoaderInstance() {
+        if (classLoaderInstance == null) {
+            synchronized (lock) {
+                if (classLoaderInstance == null) {
+                    URLClassLoader loader = createURLClassLoaderInstance();
+                    classLoaderInstance = loader;
```
Comment (trask) [inline src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java]:
```suggestion
                    classLoaderInstance = createURLClassLoaderInstance();
```

**Review by trask — DISMISSED** [review]
just two minor simplifications

**Review by trask — DISMISSED** [review]

**Review by amamounelsayed — APPROVED** [review]
