### PR TITLE
Fixes #101

### LINKED ISSUE #101: MessageHandler needs to set RPCException in case of errors
Rignt now, [MessageHandler.java#L48](https://github.com/Azure/azure-functions-java-worker/blob/278696f3752c5fce7d14c1f9bc4dd4b44f8babbc/azure-functions-java-worker/src/main/java/com/microsoft/azure/webjobs/script/handler/MessageHandler.java#L48)  sets status and message. [RPCException](https://github.com/Azure/azure-functions-language-worker-protobuf/blob/dev/src/proto/FunctionRpc.proto#L121) needs to be set as well to make sure host handles exceptions properly.

### PR DESCRIPTION
**Pull request by pragnagopa**
Fixes #101

### CODE REVIEW

File: src/main/java/com/microsoft/azure/functions/handler/MessageHandler.java [hunk 1]
```diff
@@ -47,10 +49,19 @@ public void handle() {
         } catch (Exception ex) {
             status = StatusResult.Status.Failure;
             statusMessage = ex.getMessage();
+            rpcException = RpcException.newBuilder().setMessage(ex.getMessage()).setStackTrace(ExceptionUtils.getStackTrace(ex)).build();
             this.getLogger().log(Level.WARNING, statusMessage, ex);
         }
         if (this.responseStatusMarshaller != null) {
-            StatusResult result = StatusResult.newBuilder().setStatus(status).setResult(statusMessage).build();
+            StatusResult result;
```
Comment (JunyiYi) [inline src/main/java/com/microsoft/azure/functions/handler/MessageHandler.java]: My personal preferred way (but it's OK if you use your style):
```java
StatusResult.Builder result = StatusResult.newBuilder().setStatus(status).setResult(statusMessage);
if (rpcException != null) {
    result = result.setException(rpcException);
}
this.responseStatusMarshaller.accept(this.response, result.build());
```

File: src/main/java/com/microsoft/azure/functions/handler/MessageHandler.java [hunk 2]
```diff
@@ -47,10 +49,19 @@ public void handle() {
...
+            if(rpcException != null)
+            {
```
Comment (JunyiYi) [inline src/main/java/com/microsoft/azure/functions/handler/MessageHandler.java]: Java Coding Style (different from C#): do not create new lines before "{".

File: src/main/java/com/microsoft/azure/functions/handler/MessageHandler.java [hunk 3]
```diff
@@ -47,10 +49,19 @@ public void handle() {
...
+                result = StatusResult.newBuilder().setStatus(status).setResult(statusMessage).setException(rpcException).build();
+            }
+            else
+            {
```
Comment (JunyiYi) [inline src/main/java/com/microsoft/azure/functions/handler/MessageHandler.java]: No newline before "{" as mentioned above.
