### PR TITLE
Use a single classloader for java 11

### LINKED ISSUE #412: Java11: Static variable appears to be difference instance even though it's in the same class.
#### Repro steps

Provide the steps required to reproduce the problem:

1. Create Function.java below.
```
package com.azure.yutobo.func;

import com.microsoft.azure.functions.ExecutionContext;
import com.microsoft.azure.functions.HttpMethod;
import com.microsoft.azure.functions.HttpRequestMessage;
import com.microsoft.azure.functions.HttpResponseMessage;
import com.microsoft.azure.functions.HttpStatus;
import com.microsoft.azure.functions.annotation.AuthorizationLevel;
import com.microsoft.azure.functions.annotation.FunctionName;
import com.microsoft.azure.functions.annotation.HttpTrigger;

import java.util.Optional;

public class Function {
    static final Person person  = new Person();

    @FunctionName("foo")
    public HttpResponseMessage foo(
            @HttpTrigger(
                name = "req",
                methods = {HttpMethod.GET, HttpMethod.POST},
                authLevel = AuthorizationLevel.ANONYMOUS)
                HttpRequestMessage<Optional<String>> request,
            final ExecutionContext context) {
        context.getLogger().info("foo processed a request.");
        return request.createResponseBuilder(HttpStatus.OK).body("Foo: " + person.).build();
    }

    @FunctionName("bar")
    public HttpResponseMessage bar(
            @HttpTrigger(
                name = "req",
                methods = {HttpMethod.GET, HttpMethod.POST},
                authLevel = AuthorizationLevel.ANONYMOUS)
                HttpRequestMessage<Optional<String>> request,
            final ExecutionContext context) {
        context.getLogger().info("bar processed a request.");
        return request.createResponseBuilder(HttpStatus.OK).body("Bar: " + person).build();
    }
}
```
```
package com.azure.yutobo.func;

class Person {
    String name = "";
    int age = 18;

    Person() {}

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + age;
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Person other = (Person) obj;
        if (age != other.age)
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        } else if (!name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public String toString() {
        return "Person [age=" + age + ", name=" + name + "]";
    }
}

```

2. access Foo & Bar endpoints.

#### Expected behavior

Foo & Bar methods show the same output because they share the same class variable.

#### Actual behavior

Foo & Bar methods show the different output like below.
image

I found that there are separate class variables of Function.class in the heap.
image

And, Function.class loaded twince by the different URLClassLoader.
Apparently, you don't check whether Function.class is already loaded or not.

#### Known workarounds
I couldn't find workarounds.

#### Impact
- There appears to be no ways to share the class variable even methods are in the same class.
- I think we can't make Double-checked locked instance to get Singleton in multi-thread environment.

### PR DESCRIPTION
**Pull request by shreyas-gopalakrishna**
Fixes
- For java 11 a synchronized singleton classloader will be used
- This fixes the issue - multiple instances of the static variable even though it's in the same class

Code changes
- Creating a singleton of the URLClassLoader which will be reused as necessary. 
- In order to handle synchronization across threads, the double checked locking with singleton is done.
- Using the volatile keyword to avoid any cache incoherence issues
- Test cases are updated to check if static variables are updated under the same instance

#412

### CODE REVIEW

File: src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java [hunk 1]
```diff
@@ -73,4 +88,5 @@ public void addUrl(URL url) throws IOException {
         urls.add(url);
     }
     private final Set<URL> urls;
+    private static volatile URLClassLoader classLoaderInstance;
```
Comment (shreyas-gopalakrishna) [inline src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java:83]: Using the volatile keyword to avoid any cache incoherence issues. Review if this is necessary for our use case

File: src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java [hunk 2]
```diff
@@ -73,4 +88,5 @@ public void addUrl(URL url) throws IOException {
         urls.add(url);
     }
     private final Set<URL> urls;
```
Comment (trask) [inline src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java:81]:
```suggestion
    private final Set<URL> urls;
    private final Object lock = new Object();
```

File: src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java [hunk 3]
```diff
@@ -22,11 +22,26 @@ public ClassLoader createClassLoader() {
...
         return classLoader;
     }
 
+    /**
+     * @param urlsForClassLoader Array of URLs to construct a new URLClassLoader
+     * @return single instance of URLClassLoader
+     */
+    private URLClassLoader getURLClassLoaderInstance(URL[] urlsForClassLoader) {
+        if (classLoaderInstance == null) {
+            synchronized (URLClassLoader.class) {
```
Comment (trask) [inline src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java]:
```suggestion
            synchronized (lock) {
```

File: src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java [hunk 4]
```diff
@@ -22,11 +22,26 @@ public ClassLoader createClassLoader() {
...
-        loadDrivers(classLoader);
+        URLClassLoader classLoader = getURLClassLoaderInstance(urlsForClassLoader);
         return classLoader;
     }
 
+    /**
+     * @param urlsForClassLoader Array of URLs to construct a new URLClassLoader
+     * @return single instance of URLClassLoader
+     */
+    private URLClassLoader getURLClassLoaderInstance(URL[] urlsForClassLoader) {
```
Comment (trask) [inline src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java]: no need to pass args here, calculate below instead

File: src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java [hunk 5]
```diff
@@ -19,12 +19,25 @@ public EnhancedClassLoaderProvider() {
      */
     @Override
     public ClassLoader createClassLoader() {
-        URL[] urlsForClassLoader = new URL[urls.size()];
-        urls.toArray(urlsForClassLoader);
+        return createURLClassLoaderInstance();
```
Comment (trask) [inline src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java]: just a style thought, can inline the `createURLClassLoaderInstance` method here

File: src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java [hunk 6]
```diff
@@ -19,12 +19,25 @@ public EnhancedClassLoaderProvider() {
...
+     * @return instance of URLClassLoader
+     */
+    private URLClassLoader createURLClassLoaderInstance() {
+        if (classLoaderInstance == null) {
+            synchronized (lock) {
+                if (classLoaderInstance == null) {
+                    URL[] urlsForClassLoader = new URL[urls.size()];
+                    urls.toArray(urlsForClassLoader);
+                    classLoaderInstance = new URLClassLoader(urlsForClassLoader);
+                    loadDrivers(classLoaderInstance);
```
Comment (trask) [inline src/main/java/com/microsoft/azure/functions/worker/reflect/EnhancedClassLoaderProvider.java]: good to assign the field at the very end, so that another thread can't come in and return `classLoaderInstance` prior to it being fully initialized
```suggestion
                    URLClassLoader loader = new URLClassLoader(urlsForClassLoader);
                    loadDrivers(loader);
                    classLoaderInstance = loader;
```

**Review by trask — DISMISSED** [review]

**Review by amamounelsayed — DISMISSED** [review]

**Review by trask — APPROVED** [review]

**Review by amamounelsayed — APPROVED** [review]
